//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramlama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public Uyeler()
        {
            this.Favoriler = new HashSet<Favoriler>();
            this.Satislar = new HashSet<Satislar>();
            this.Satislar1 = new HashSet<Satislar>();
            this.Urunler = new HashSet<Urunler>();
        }
    
        public int UyeID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string Sehir { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> DegerPuani { get; set; }
        public string Fotograf { get; set; }
    
        public virtual ICollection<Favoriler> Favoriler { get; set; }
        public virtual ICollection<Satislar> Satislar { get; set; }
        public virtual ICollection<Satislar> Satislar1 { get; set; }
        public virtual ICollection<Urunler> Urunler { get; set; }
    }
}
